name = "Gcvspl"
uuid = "0df96c42-4702-4aad-9d07-874ea0467d1e"
authors = ["Charles Le Losq <lelosq@ipgp.fr>"]
version = "0.1.0"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1.0"
